[build]
  publish = "app"
  command = "echo 'hello world!'"
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[headers]]
  for = "/js/*"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"
    Content-Type = "application/javascript; charset=UTF-8"
    f-foo = "hello world!"

